backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
collections:
  - name: home
    label: Home
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: mission
    label: Mission
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: what-we-do
    label: What We Do
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: clinic-schedule
    label: Clinic Schedule
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: clinic-trip-checklist
    label: Clinic Trip Checklist
    folder: public/content/pages/resources
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: emergency-contacts
    label: Emergency Contacts
    folder: public/content/pages/resources
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: links
    label: Links
    folder: public/content/pages/resources
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: pilot-information
    label: Pilot Information
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: contact
    label: Contact
    folder: public/content/pages
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
  - name: collection1
    label: Team of Airplanes
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection2
    label: Colorado Team
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection3
    label: Flying to Mexico
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection4
    label: Patients Waiting for Eye Clinic
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection5
    label: Optometry Clinic
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection6
    label: Eye Surgery Clinic
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection7
    label: Spiritual Ministry
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
  - name: collection8
    label: Celebrating a Successful Clinic
    folder: public/content/pages/resources/videos-and-photos
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: images
        label: Images
        widget: list
        fields:
          - name: image
            label: Image
            widget: image
site_config:
  name: site-config
  file: data/site-config.json
  label: Site Configuration
  create: true
  delete: true
  editor:
    preview: true
  fields:
    - name: title
      label: Site Title
      widget: string
    - name: metaDescription
      label: Meta Description
      widget: text
