backend:
  name: git-gateway
  branch: main

media_folder: static/uploads
public_folder: /uploads

collections:
  -name: 'home'
  label: 'Home'
  folder: 'content/pages/home'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'mission'
  label: 'Mission'
  folder: 'content/pages/mission'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'what-we-do'
  label: 'What We Do'
  folder: 'content/pages/what-we-do'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'clinic-schedule'
  label: 'Clinic Schedule'
  folder: 'content/pages/clinic-schedule'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'clinic-trip-checklist'
  label: 'Clinic Trip Checklist'
  folder: 'content/pages/resources/clinic-trip-checklist'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'emergency-contacts'
  label: 'Emergency Contacts'
  folder: 'content/pages/resources/emergency-contacts'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'links'
  label: 'Links'
  folder: 'content/pages/resources/links'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'pilot-information'
  label: 'Pilot Information'
  folder: 'content/pages/pilot-information'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }
  -name: 'contact'
  label: 'Contact'
  folder: 'content/pages/contact'
  create: true
  fields:
    { name: 'title', label: 'Title', widget: 'string' }
    { name: 'body', label: 'Body', widget: 'markdown' }

site_config:
  name: 'site-config'
  file: 'data/site-config.json'
  label: 'Site Configuration'
  create: false
  delete: false
  editor:
    preview: false
  fields:
    - { name: 'title', label: 'Site Title', widget: 'string' }
    - { name: 'metaDescription', label: 'Meta Description', widget: 'text' }
